from aiogram.dispatcher.filters.state import StatesGroup, State

class InitialTestStates(StatesGroup):
    start_initial_test = State()
    second_q = State()
    third_q = State()
    fourth_q = State()
    fifth_q = State()
    sixth_q = State()
    seventh_q = State()
    eighth_q = State()
    ninth_q = State()
    tenth_q = State()
    eleventh_q = State()
    twelfth_q = State()
    thirteenth_q = State()
    fourteenth_q = State()
    fifteenth_q = State()
    sixteenth_q = State()
    seventeenth_q = State()
    eighteenth_q = State()
    nineteenth_q = State()
    twentieth_q = State()
    twenty_first_q = State()
    twenty_second_q = State()
    twenty_third_q = State()
    twenty_fourth_q = State()
    twenty_fifth_q = State()
    end_of_initial_test = State()